upstream model_a {
    server model-a:8001;
}
upstream model_b {
    server model-b:8002;
}
upstream model_c {
    server model-c:8003;
}

server {
    listen 80;

    location /model-a/ {
        proxy_pass http://model_a/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /model-b/ {
        proxy_pass http://model_b/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /model-c/ {
        proxy_pass http://model_c/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
